name: Test

permissions:
  contents: read

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  regular_test:
    name: "Test (${{ matrix.compiler }}, C++${{ matrix.standard}}, ${{ matrix.mode }})"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
      matrix:
        # only the compilers supported by setup-cpp
        compiler: [clang++-18, gcc-13]
        standard: [20, 23]
        mode: [dev, debug, release]
    with:
      compiler: ${{ matrix.compiler }}
      standard: ${{ matrix.standard }}
      mode: ${{ matrix.mode }}
      enables: ${{ matrix.enables }}
      options: ${{ matrix.options }}
  build_with_dpdk:
    name: "Test with DPDK enabled"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
    with:
      compiler: clang++-18
      standard: 23
      mode: release
      enables: --enable-dpdk
      options: --cook dpdk --dpdk-machine haswell
  build_with_cxx_modules:
    name: "Test with C++20 modules enabled"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
    with:
      compiler: clang++-18
      standard: 23
      mode: debug
      enables: --enable-cxx-modules
