name: Test

permissions:
  contents: read

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  regular_test:
    name: "Test (${{ matrix.compiler }}, C++${{ matrix.standard}}, ${{ matrix.mode }}, ${{ matrix.crypto_provider }})"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++, g++]
        standard: [20, 23]
        mode: [dev, debug, release]
        crypto_provider: [GnuTLS, OpenSSL]
    with:
      compiler: ${{ matrix.compiler }}
      standard: ${{ matrix.standard }}
      mode: ${{ matrix.mode }}
      enables: ${{ matrix.enables }}
      options: ${{ matrix.options }}
      crypto_provider: ${{ matrix.crypto_provider }}
  build_with_dpdk:
    name: "Test with DPDK enabled"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
    with:
      compiler: clang++
      standard: 23
      mode: release
      enables: --enable-dpdk
      options: --cook dpdk
  build_with_cxx_modules_gnutls:
    name: "Test with C++20 modules enabled (GnuTLS)"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
    with:
      compiler: clang++
      standard: 23
      mode: debug
      enables: --enable-cxx-modules
      enable-ccache: false
      crypto_provider: GnuTLS
    # disable modules build as we aren't using module and it is quite
    # broken at the moment
    if: false
  build_with_cxx_modules_openssl:
    name: "Test with C++20 modules enabled (OpenSSL)"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
    with:
      compiler: clang++
      standard: 23
      mode: debug
      enables: --enable-cxx-modules
      enable-ccache: false
      crypto_provider: OpenSSL
    # disable modules build as we aren't using module and it is quite
    # broken at the moment
    if: false
